//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.LocalizationFile", typeof(LocalizationFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Silindi!.
        /// </summary>
        public static string BrandDeletedText {
            get {
                return ResourceManager.GetString("BrandDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Düzenlendi!.
        /// </summary>
        public static string BrandUpdatedText {
            get {
                return ResourceManager.GetString("BrandUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Adı.
        /// </summary>
        public static string CampaignNameText {
            get {
                return ResourceManager.GetString("CampaignNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renk.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        public static string CreationDateTime {
            get {
                return ResourceManager.GetString("CreationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Oluşturuldu!.
        /// </summary>
        public static string CustomerCreateText {
            get {
                return ResourceManager.GetString("CustomerCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Silindi!.
        /// </summary>
        public static string CustomerDeleteText {
            get {
                return ResourceManager.GetString("CustomerDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Düzenlendi!.
        /// </summary>
        public static string CustomerUpdateText {
            get {
                return ResourceManager.GetString("CustomerUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Oluşturuldu!.
        /// </summary>
        public static string EmployeeCreateText {
            get {
                return ResourceManager.GetString("EmployeeCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Silindi!.
        /// </summary>
        public static string EmployeeDeleteText {
            get {
                return ResourceManager.GetString("EmployeeDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Düzenlenid!.
        /// </summary>
        public static string EmployeeUpdateText {
            get {
                return ResourceManager.GetString("EmployeeUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silindi Mi?.
        /// </summary>
        public static string IsDelete {
            get {
                return ResourceManager.GetString("IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Giriş Tarihi.
        /// </summary>
        public static string LastLoginDateTime {
            get {
                return ResourceManager.GetString("LastLoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Adlı Model Silindi!.
        /// </summary>
        public static string ModelDeletedText {
            get {
                return ResourceManager.GetString("ModelDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Düzenlendi!.
        /// </summary>
        public static string ModelUpdatedText {
            get {
                return ResourceManager.GetString("ModelUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik Numarası.
        /// </summary>
        public static string NationalIdentityNumber {
            get {
                return ResourceManager.GetString("NationalIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Kaydı Oluşturuldu!.
        /// </summary>
        public static string ParkDetailCreateText {
            get {
                return ResourceManager.GetString("ParkDetailCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı bilgiler Park Geçmişine kayıt edildi!.
        /// </summary>
        public static string ParkDetailFinished {
            get {
                return ResourceManager.GetString("ParkDetailFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Bitiş Tarihi.
        /// </summary>
        public static string ParkedLeaveDateTime {
            get {
                return ResourceManager.GetString("ParkedLeaveDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Başlangıç Tarihi.
        /// </summary>
        public static string ParkingStartDateTime {
            get {
                return ResourceManager.GetString("ParkingStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Alanı.
        /// </summary>
        public static string ParkPlaceNameText {
            get {
                return ResourceManager.GetString("ParkPlaceNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif.
        /// </summary>
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaka.
        /// </summary>
        public static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde belirtilen araç tipine uygun fiyatlandırma bilgisi bulunamamıştır. Lütfen fiyatı &apos;Fiyat&apos; adlı metin kutusuna eliniz ile giriniz!\nNot: En kısa zamanda belirtilen araç tipine ait bir fiyatlandırma girmenizi öneririz, aksi halde bu mesaj tekrarlanacaktır..
        /// </summary>
        public static string PriceCalculateNotFoundText {
            get {
                return ResourceManager.GetString("PriceCalculateNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park saatine uygun sistemde fiyatlandırma kaydı bulunamadı. Fiyatı elinizle girmek ister misiniz? (Hayır denirse varsa en yüksek ödeme çekilecek).
        /// </summary>
        public static string PriceMethodQuestionText {
            get {
                return ResourceManager.GetString("PriceMethodQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru.
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı veya Şifre Yanlış!.
        /// </summary>
        public static string UsernameorPasswordIncorrectText {
            get {
                return ResourceManager.GetString("UsernameorPasswordIncorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Plakalı Araç Sisteme Kayıt Edildi!.
        /// </summary>
        public static string VehicleCreatedText {
            get {
                return ResourceManager.GetString("VehicleCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Plakalı Taşıt Başarıyla Silindi!.
        /// </summary>
        public static string VehicleDeletedText {
            get {
                return ResourceManager.GetString("VehicleDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0} Plakalı Taşıt Silinsin Mi?.
        /// </summary>
        public static string VehicleDeleteQuestionText {
            get {
                return ResourceManager.GetString("VehicleDeleteQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Plaka Sistemde Kayıtlı!.
        /// </summary>
        public static string VehiclePlateAlreadyRegisteredText {
            get {
                return ResourceManager.GetString("VehiclePlateAlreadyRegisteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyatlandırma Sisteme Kayıt Edildi!.
        /// </summary>
        public static string VehiclePriceCreatedText {
            get {
                return ResourceManager.GetString("VehiclePriceCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Id&apos;li Fiyatlandırma Silindi!.
        /// </summary>
        public static string VehiclePriceDeletedText {
            get {
                return ResourceManager.GetString("VehiclePriceDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyatlandırma Düzenlendi!.
        /// </summary>
        public static string VehiclePriceUpdatedText {
            get {
                return ResourceManager.GetString("VehiclePriceUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıt Tipi Oluşturuldu!.
        /// </summary>
        public static string VehicleTypeCreateText {
            get {
                return ResourceManager.GetString("VehicleTypeCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Adlı Taşıt Başarıyla Silindi!.
        /// </summary>
        public static string VehicleTypeDeletedText {
            get {
                return ResourceManager.GetString("VehicleTypeDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Adlı Taşıt Silinsin Mi?.
        /// </summary>
        public static string VehicleTypeDeleteQuestionText {
            get {
                return ResourceManager.GetString("VehicleTypeDeleteQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıt Adı.
        /// </summary>
        public static string VehicleTypeNameText {
            get {
                return ResourceManager.GetString("VehicleTypeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıt Tipi.
        /// </summary>
        public static string VehicleTypeText {
            get {
                return ResourceManager.GetString("VehicleTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Adlı Taşıt Düzenlendi!.
        /// </summary>
        public static string VehicleTypeUpdatedText {
            get {
                return ResourceManager.GetString("VehicleTypeUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Plakalı Taşıt Düzenlendi!.
        /// </summary>
        public static string VehicleUpdatedText {
            get {
                return ResourceManager.GetString("VehicleUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
